### ISSUE TITLE
Döviz kurları hk.

### ISSUE THREAD

**Issue by ByErdem** [mewebstudio/tcmb-doviz#1]
Merhaba,
Ben php bilmiyorum. Javascript ile bunu kullanmamın yolu var mı? İlginiz için şimdiden teşekkürler.

**Comment by mewebstudio** [comment]
Geç cevap için özür dilerim.
Javascript ile ancak şu şekilde kullanabilirsiniz:
Buradaki kodlarla, php çalıştıran bir sunucudan json veya xml çıktı üreten basit bir websevis yazarsınız.
Javascript tarafında axios veya jquery'nin ajax metoduyla webservise istekte bulunup gelen veriyi kullanırsınız.
